## Handling Imbalanced Dataset

- pip install imbalanced-learn

In [1]:
import pandas as pd
df = pd.read_csv('Datasets/creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [2]:
df.shape

(284807, 31)

In [3]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [4]:
## Independent and Dependent Features
X = df.drop("Class",axis=1)
y = df.Class 

### When Dealing with Imbalanced Dataset go with using *Cross Validation* like *KFold* and *Hyperparameter Tuning*

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np 
from sklearn.model_selection import GridSearchCV

In [6]:
logistic_regression = LogisticRegression()
grid = {
    'C': 10.0**np.arange(-2,3),
    'penalty': ['l1','l2'],     
}

cv = KFold(n_splits=5,random_state=None,shuffle=False)



In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [8]:
clf = GridSearchCV(logistic_regression,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(X_train,y_train)

c:\Users\Yash\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Yash\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Yash\anaconda3\Lib\site-packages\sklearn\base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Yash\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1172, in fit
    solver = _chec

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [9]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85235    52]
 [   54   102]]
0.9987594068560327
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85287
           1       0.66      0.65      0.66       156

    accuracy                           1.00     85443
   macro avg       0.83      0.83      0.83     85443
weighted avg       1.00      1.00      1.00     85443



In [10]:
## trying RandomForest
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [11]:
y_pred = rf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85285     2]
 [   39   117]]
0.9995201479348805
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85287
           1       0.98      0.75      0.85       156

    accuracy                           1.00     85443
   macro avg       0.99      0.87      0.93     85443
weighted avg       1.00      1.00      1.00     85443



It is performing better than LogisticRegression

In [12]:
class_weight = dict({
    0:1,
    1:100
})

In [13]:
## trying RandomForest with Class Weight
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(class_weight=class_weight)
rf.fit(X_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [14]:
y_pred = rf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85285     2]
 [   40   116]]
0.9995084442259752
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85287
           1       0.98      0.74      0.85       156

    accuracy                           1.00     85443
   macro avg       0.99      0.87      0.92     85443
weighted avg       1.00      1.00      1.00     85443



- When we have high imbalanced dataset then we can use the concept of class weight.
- Try to use this way at last.

#### Under Sampling
- Undersampling -> reduce the points of maximum labels

In [15]:
y_train.value_counts()

Class
0    199028
1       336
Name: count, dtype: int64

In [16]:
from collections import Counter

from imblearn.under_sampling import NearMiss
ns = NearMiss(sampling_strategy=0.8)

X_train_ns,y_train_ns = ns.fit_resample(X_train,y_train)

print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes before fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({0: 199028, 1: 336})
The number of classes before fit Counter({0: 420, 1: 336})


In [17]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [18]:
y_pred = rf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[64745 20542]
 [   12   144]]
0.7594419671593928
              precision    recall  f1-score   support

           0       1.00      0.76      0.86     85287
           1       0.01      0.92      0.01       156

    accuracy                           0.76     85443
   macro avg       0.50      0.84      0.44     85443
weighted avg       1.00      0.76      0.86     85443



#### Over Sampling

In [19]:
from imblearn.over_sampling import RandomOverSampler

In [20]:
os = RandomOverSampler(sampling_strategy=0.5)

X_train_os,y_train_os = os.fit_resample(X_train,y_train)

print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes before fit {}".format(Counter(y_train_os)))

## In oversampling we increase the values in class where we have low value....

The number of classes before fit Counter({0: 199028, 1: 336})
The number of classes before fit Counter({0: 199028, 1: 99514})


In [21]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_os,y_train_os)

y_pred = rf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85281     6]
 [   35   121]]
0.9995201479348805
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85287
           1       0.95      0.78      0.86       156

    accuracy                           1.00     85443
   macro avg       0.98      0.89      0.93     85443
weighted avg       1.00      1.00      1.00     85443



#### SMOTETomek

In [22]:
from imblearn.combine import SMOTETomek

In [23]:
os = SMOTETomek(sampling_strategy=0.5) ## SMOTETomek uses the both concept of undersamplng and oversampling...

X_train_os,y_train_os = os.fit_resample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes before fit {}".format(Counter(y_train_os)))

The number of classes before fit Counter({0: 199028, 1: 336})
The number of classes before fit Counter({0: 198180, 1: 98666})


In [24]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_os,y_train_os)

y_pred = rf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85271    16]
 [   26   130]]
0.9995084442259752
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85287
           1       0.89      0.83      0.86       156

    accuracy                           1.00     85443
   macro avg       0.95      0.92      0.93     85443
weighted avg       1.00      1.00      1.00     85443



##### Ensemble Techniques

In [ ]:
from imblearn.ensemble import EasyEnsembleClassifier

In [26]:
easy = EasyEnsembleClassifier()
easy.fit(X_train,y_train)

EasyEnsembleClassifier()